services:
  # service1:
  #     build:
  #       context: ./service1
  #       dockerfile: Dockerfile
  #     ports:
  #       - "8080:8080"
  #     networks:
  #       - tracing-spring-zipkin
  # service2:
  #     build:
  #       context: ./service2
  #       dockerfile: Dockerfile
  #     ports:
  #       - "8081:8081"
  #     networks:
  #       - tracing-spring-zipkin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - tracing-spring-zipkin

networks:
  tracing-spring-zipkin:
    driver: bridge
